codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "40...100"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

ignore:
  - "src/framework/tests/*"
  - "src/main/app.py"
  - "tests/*"

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false
