codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  range: "0...100"
  round: down
  status:
    project:
      default:
        only_pulls: true
        target: 50%
        threshold: 100%

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

ignore:
  - "src/framework/tests/*"
  - "src/main/app.py"
  - "tests/*"

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false
