name: DockerHub Push

on:
  workflow_dispatch:

jobs:
  docker:
    if: github.actor == 'tgrx'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Get build args
        id: build-args
        run: |
          echo ::set-output name=python_version::$(cat .python-version)
          echo ::set-output name=version::$(cat version.txt)
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          build-args: |
            python_version=${{ steps.build-args.outputs.python_version }}
            version=${{ steps.build-args.outputs.version }}
          context: .
          push: true
          tags: |
            alexandersidorov/alpha:${{ steps.build-args.outputs.version }}
            alexandersidorov/alpha:latest
